# Generated by Django 4.2.11 on 2025-06-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pics/user.png', null=True, upload_to='profile_pics/'),
        ),
    ]
